package:
  name: tf-encrypted
  version: "0.6.0-rc0"

source:
  git_url: https://github.com/tf-encrypted/tf-encrypted.git

  about:
    home: https://github.com/tf-encrypted/tf-encrypted
    license: APACHE-2
    license_file: LICENSE
    summary: "Layer on top of TensorFlow for doing machine learning on encrypted data."

requirements:
  run:
    - python
    - tensorflow == 2.0.0
    - numpy >= 1.14.0
